# Generated by Django 4.1.7 on 2023-08-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_week', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=50)),
                ('packageName', models.CharField(max_length=80)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('app_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_app_week', to='app_week.appweek')),
            ],
        ),
    ]
