# Generated by Django 4.1.7 on 2023-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='start_date',
            field=models.DateField(),
        ),
    ]
