# Generated by Django 4.1.7 on 2023-08-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_week', '0003_appdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appdata',
            old_name='appName',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='appdata',
            old_name='packageName',
            new_name='package_name',
        ),
    ]
