# Generated by Django 3.2.22 on 2023-11-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_deviceapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date_time', models.DateTimeField()),
                ('is_hourly', models.BooleanField(default=False)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_device_app_block', to='device.device')),
            ],
        ),
    ]
