# Generated by Django 4.1.7 on 2023-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_device_code_alter_device_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=50),
        ),
    ]
