# Generated by Django 4.1.7 on 2023-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpairdevice',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='userpairdevice',
            name='pair_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=100),
        ),
    ]
