# Generated by Django 4.1.7 on 2023-05-13 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_userprofile_child_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='child_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='parent_user',
        ),
        migrations.CreateModel(
            name='UserPairDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('user_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pair_device', to=settings.AUTH_USER_MODEL)),
                ('user_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
