# Generated by Django 4.1.7 on 2023-05-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_child_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pair_device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userpairdevice'),
        ),
    ]
