# Generated by Django 4.1.7 on 2023-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_pair_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pair_device',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pair_device',
            field=models.ManyToManyField(to='user_profile.userpairdevice'),
        ),
    ]
