# Generated by Django 4.1.7 on 2023-05-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_userprofile_pair_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pair_device',
        ),
    ]
