# Generated by Django 4.1.7 on 2023-05-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_userprofile_pair_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpairdevice',
            name='user_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pair_device', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='userpairdevice',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_device', to='user_profile.userprofile'),
        ),
    ]
