# Generated by Django 4.1.7 on 2023-08-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userpairdevice_user_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
